export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
export const REMOVE_AUTHENTICATED_USER = 'REMOVE_AUTHENTICATED_USER';