export const notificationConstants = {
    ADD_NOTIFICATION: 'ADD_NOTIFICATION',
    REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
    SET_AUTHENTICATED_USER: 'SET_AUTHENTICATED_USER',
    REMOVE_AUTHENTICATED_USER: 'REMOVE_AUTHENTICATED_USER',
}